name: flutter_flavor_setup
description: A comprehensive tool for setting up and managing flavors (environments) in Flutter projects for both Android and iOS.
version: 1.0.0
homepage: https://github.com/AbdallahAbusnineh/flutter_flavor_setup
repository: https://github.com/AbdallahAbusnineh/flutter_flavor_setup
issue_tracker: https://github.com/AbdallahAbusnineh/flutter_flavor_setup/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

executables:
  setup_flavors:
flutter:
  uses-material-design: true
